// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexGrades.Data;

#nullable disable

namespace NexGrades.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801121237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("NexGrades.Data.Entities.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.BucketTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("BucketTemplates", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CohortLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FoundedInSchoolYearId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoundedInSchoolYearId");

                    b.ToTable("ClassGroups", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.ClassInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ClassGroupId", "SchoolYearId")
                        .IsUnique();

                    b.ToTable("ClassInstances", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeftOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassInstanceId");

                    b.HasIndex("StudentId", "ClassInstanceId")
                        .IsUnique();

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int>("GradeBucketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RecordedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GradeBucketId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.GradeBucket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectInstanceId");

                    b.ToTable("GradeBuckets", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClassInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastEditedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassInstanceId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("StudentId");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.SchoolYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnlockedUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SchoolYears", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.SubjectInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ClassInstanceId", "SubjectId")
                        .IsUnique();

                    b.ToTable("SubjectInstances", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.SubjectParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("From")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectInstanceId");

                    b.ToTable("SubjectParticipations", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("NexGrades.Data.Entities.BucketTemplate", b =>
                {
                    b.HasOne("NexGrades.Data.Entities.Subject", "Subject")
                        .WithMany("BucketTemplates")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.ClassGroup", b =>
                {
                    b.HasOne("NexGrades.Data.Entities.SchoolYear", "FoundedInSchoolYear")
                        .WithMany("FoundedClassGroups")
                        .HasForeignKey("FoundedInSchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoundedInSchoolYear");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.ClassInstance", b =>
                {
                    b.HasOne("NexGrades.Data.Entities.ClassGroup", "ClassGroup")
                        .WithMany("ClassInstances")
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexGrades.Data.Entities.SchoolYear", "SchoolYear")
                        .WithMany("ClassInstances")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexGrades.Data.Entities.Teacher", "Teacher")
                        .WithMany("ClassInstances")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClassGroup");

                    b.Navigation("SchoolYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Enrollment", b =>
                {
                    b.HasOne("NexGrades.Data.Entities.ClassInstance", "ClassInstance")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexGrades.Data.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassInstance");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Grade", b =>
                {
                    b.HasOne("NexGrades.Data.Entities.GradeBucket", "GradeBucket")
                        .WithMany("Grades")
                        .HasForeignKey("GradeBucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexGrades.Data.Entities.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradeBucket");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.GradeBucket", b =>
                {
                    b.HasOne("NexGrades.Data.Entities.SubjectInstance", "SubjectInstance")
                        .WithMany("GradeBuckets")
                        .HasForeignKey("SubjectInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubjectInstance");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Note", b =>
                {
                    b.HasOne("NexGrades.Data.Entities.ClassInstance", "ClassInstance")
                        .WithMany("Notes")
                        .HasForeignKey("ClassInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexGrades.Data.Entities.SchoolYear", "SchoolYear")
                        .WithMany("Notes")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexGrades.Data.Entities.Student", "Student")
                        .WithMany("Notes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassInstance");

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.SubjectInstance", b =>
                {
                    b.HasOne("NexGrades.Data.Entities.ClassInstance", "ClassInstance")
                        .WithMany("SubjectInstances")
                        .HasForeignKey("ClassInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexGrades.Data.Entities.Subject", "Subject")
                        .WithMany("SubjectInstances")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexGrades.Data.Entities.Teacher", "Teacher")
                        .WithMany("SubjectInstances")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClassInstance");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.SubjectParticipation", b =>
                {
                    b.HasOne("NexGrades.Data.Entities.Student", "Student")
                        .WithMany("SubjectParticipations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexGrades.Data.Entities.SubjectInstance", "SubjectInstance")
                        .WithMany("SubjectParticipations")
                        .HasForeignKey("SubjectInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("SubjectInstance");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.ClassGroup", b =>
                {
                    b.Navigation("ClassInstances");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.ClassInstance", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Notes");

                    b.Navigation("SubjectInstances");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.GradeBucket", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.SchoolYear", b =>
                {
                    b.Navigation("ClassInstances");

                    b.Navigation("FoundedClassGroups");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Grades");

                    b.Navigation("Notes");

                    b.Navigation("SubjectParticipations");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Subject", b =>
                {
                    b.Navigation("BucketTemplates");

                    b.Navigation("SubjectInstances");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.SubjectInstance", b =>
                {
                    b.Navigation("GradeBuckets");

                    b.Navigation("SubjectParticipations");
                });

            modelBuilder.Entity("NexGrades.Data.Entities.Teacher", b =>
                {
                    b.Navigation("ClassInstances");

                    b.Navigation("SubjectInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
